# Generated by Django 5.2 on 2025-04-28 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
        migrations.AddField(
            model_name='posts',
            name='contenu_texte',
            field=models.CharField(default='empty', max_length=200),
        ),
        migrations.AddField(
            model_name='posts',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posts',
            name='ddate_modification',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posts',
            name='media',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
