# Generated by Django 5.2 on 2025-04-28 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_posts_date_posts_contenu_texte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='ddate_modification',
        ),
        migrations.AddField(
            model_name='posts',
            name='date_modification',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
