# Generated by Django 5.2 on 2025-04-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_likes_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.posts'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.posts'),
        ),
    ]
